<?php

require_once 'People.php';
require_once 'IActions.php';
class Watching extends People
{
    private $pay;

    public function __construct($name, $age, $pay)
    {
        parent::__construct($name, $age);

        if (!empty($pay)){
            $this->pay=$pay;
        }else{
            $this->pay=0;
            return '<br>Не введена сумма заплаченых денег за спектакль в классе Watching';
        }
    }

    public function setPay($pay){
        if (!empty($pay)){
            $this->pay=$pay;
        }else{
            $this->pay=0;
            return '<br>Не введена сумма заплаченых денег за спектакль в классе Watching';
        }
    }

    public function getPay(){
        return $this->pay;
    }

    public function show()
    {
        return parent::show().'<br>Я заплатил за спектакль - '.$this->getPay(); // TODO: Change the autogenerated stub
    }
}